# Generated by Django 5.0.6 on 2024-07-04 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('salary_range', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999999999)])),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(max_length=20, null=True, unique=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('department_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department')),
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.job')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(blank=True, max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=200)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('benefit_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('benefit_type', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('attendence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True)),
                ('check_in_time', models.DateTimeField(blank=True)),
                ('check_out_time', models.DateField(blank=True)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salary', models.PositiveBigIntegerField(blank=True)),
                ('bonus', models.PositiveBigIntegerField(blank=True)),
                ('deduction', models.PositiveBigIntegerField(blank=True)),
                ('paydate', models.DateField(blank=True)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reviewdate', models.DateField(blank=True)),
                ('score', models.PositiveBigIntegerField(blank=True)),
                ('feedback', models.TextField(blank=True, max_length=200)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('training_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('training_name', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('p', 'pass'), ('f', 'fail')], max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('employee_id', models.ManyToManyField(related_name='trainings', to='hr.employee')),
            ],
        ),
    ]
