# Generated by Django 5.0.6 on 2024-07-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, default='peshawar', max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='kashif@email.com', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(default='kashif', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(default='027830974692', max_length=20, unique=True),
        ),
    ]
