# Generated by Django 5.0.6 on 2024-07-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_address_alter_employee_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary_range',
            field=models.JSONField(),
        ),
    ]
