# Generated by Django 5.0.6 on 2024-07-17 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_employee_department_id_alter_employee_job_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee'),
        ),
    ]
